--- # 该模块的名称，在服务模块创建时将使用该名称
whooshing.template-privilege-system:
    # 该模块的根域名 (二级域名)
    # 若设置为 template，则访问域名将为 "template.whooshings.space"
    domain: "template"
    # 填写 PostgreSQL 数据库的配置
    # 你可以创建多个数据库连接，此处默认创建两个
    pgsql:
        # 数据库服务的配置名称，可随意指定，将作为 FluentKit 的 DatabaseID 识别
        # 在服务内使用时，使用该名称即可获取数据库连接实例
        "default":
            # 要连接的数据库名称，一个数据库服务可以有多个数据库
            # 在 Server 中可以通过 "\(PGSQL.name)/\(DB.name)" 访问
            # 在此例中，其 DatabaseID 分别为 "default/postgres" 和 "default/file_storage"
            databases: ["postgres", "file_storage"]
            # 指定 PostgreSQL 的服务端口 (1~19)
            # 每个服务模块都有内部分配的 20 个端口，因此你只需要指定相对端口即可
            port: 0
        "pg2":
            databases: ["testing2"]
            port: 10
    # 服务模块的捆绑包
    # 可以为不同的子模块分别指定配置
    # 你可以指定多个
    # 可配置的子模块有 API 和 HTTPS
    service_bundles:
        # 服务模块的名称，你可以随意指定
        service1:
            # api 模块配置块
            api:
                # 该模块的运行端口(相对端口)
                port: 1
                # 该模块所绑定的主机名或 ipv4 地址，可选，默认为 localhost
                hostname: "localhost"
                # 该模块将连接的数据库(相对端口)
                pg_database_ports: [0, 10]
                # 该模块的三级域名，本例的配置中，你可以通过
                # "api.template.whooshings.space" 访问该模块
                domain: "api"
            # https 模块配置块
            https:
                port: 3
                # 可选，默认为 localhost
                hostname: "localhost"
                pg_database_ports: [0]
                domain: "web"
            # 该服务模块的捆绑包位置，不要改动该配置，除非你知道你在做什么
            path: "./bundle"
    # INLINE 子模块的配置块
    shared_inline_module:
        # 该模块将连接的数据库(相对端口)
        port: 2
        # 该模块将连接的数据库(相对端口)
        pg_database_ports: [0, 10]
