name: Release and Package Workflow

on:
  release:
    types: [published]

jobs:
  release-and-package:
    uses: whooshing-workshop/ci/.github/workflows/release.yml@develop
    with:
      work_dir: "."
      app_name: "App"
    secrets:
      RELEASE_ACCESS: ${{ secrets.CLWANG_RELEASE_ACCESS }}
